name: artepix_smart_packaging
description: ARTEPIX Smart Packaging - E-Commerce Kemasan Custom dengan AI Design Studio
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core
  cupertino_icons: ^1.0.6
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Navigation
  go_router: ^13.0.0
  
  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  
  # Animations
  rive: ^0.13.0
  lottie: ^2.7.0
  flutter_animate: ^4.3.0
  
  # 3D Viewer (Phase 2)
  # 3D Viewer (Phase 2)
  # model_viewer_plus: ^1.7.2
  
  # Utils
  intl: ^0.18.1
  google_fonts: ^6.1.0
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # Network (untuk API nanti)
  dio: ^5.4.0
  
  # Icons
  iconsax: ^0.0.8
  
  # Google Sign-In
  google_sign_in: ^6.2.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/3d_models/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/static/Inter_18pt-Regular.ttf
        - asset: assets/fonts/static/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/static/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/static/Inter_18pt-Bold.ttf
          weight: 700
    - family: Outfit
      fonts:
        - asset: assets/fonts/static/Outfit-Regular.ttf
        - asset: assets/fonts/static/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/static/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/static/Outfit-Bold.ttf
          weight: 700
